import { Project } from "@/types/project";

const projects: Project[] = [
    {
        id: 1,
        title: "Plaza Lama E-Commerce Dashboard",
        description: "E-commerce dashboard developed from scratch, replacing an old Angular version with significant performance improvements.",
        longDescription:
            "This e-commerce dashboard was created completely from scratch for Plaza Lama, replacing a previous version developed in an obsolete version of Angular. The project improved performance by more than 200% and automated numerous processes. Implemented with framework best practices, it features a responsive interface, inventory management, and uses mocks for API calls during development. To log in, use username: admin and password: admin",
        image: "/projects/frontend-1.webp",
        gallery: [
            "/projects/frontend-1.webp",
            "/projects/frontend-2.webp",
            "/projects/frontend-3.webp",
            "/projects/frontend-4.webp",
            "/projects/frontend-5.webp",
        ],
        tags: ["React", "TypeScript", "Tailwind CSS", "Vite", "Tanstack", "Radix", "Zod"],
        demoUrl: "https://cm-dashboard-frontend.netlify.app/",
        githubUrl: "https://github.com/CamiloMaria/dashboard-frontend",
        featured: true,
        category: "frontend",
    },
    {
        id: 2,
        title: "E-Commerce Dashboard Backend",
        description: "Backend API developed with NestJS to support all functionalities of the Plaza Lama e-commerce dashboard.",
        longDescription:
            "This project constitutes the backend that connects all the frontend dashboard logic for Plaza Lama. Developed with NestJS best practices, it implements a robust architecture to manage authentication, authorization, and all business operations. It uses TypeORM as ORM for database management, JWT for authentication, Winston for logging, and is fully tested with Jest.",
        image: "/projects/backend-1.webp",
        gallery: [
            "/projects/backend-1.webp",
            "/projects/backend-2.webp",
            "/projects/backend-3.webp",
            "/projects/backend-4.webp",
            "/projects/backend-5.webp",
        ],
        tags: ["NestJS", "TypeScript", "Node.js", "TypeORM", "JWT", "RxJS", "Jest"],
        githubUrl: "https://github.com/CamiloMaria/dashboard-backend",
        featured: true,
        category: "backend",
    },
    {
        id: 3,
        title: "Personal Portfolio",
        description: "Personal portfolio website developed with Next.js, TypeScript and Tailwind CSS with interactive animations and responsive design.",
        longDescription:
            "This personal portfolio was designed and developed from scratch using modern technologies to create an attractive and professional web experience. It features sections to showcase projects, skills, experience, and testimonials. Implemented with smooth animations using Framer Motion and a fully responsive design that adapts to any device. The project is structured following frontend development best practices and demonstrates advanced skills in React and TypeScript.",
        image: "/projects/portafolio-1.webp",
        gallery: [
            "/projects/portafolio-1.webp",
            "/projects/portafolio-2.webp",
            "/projects/portafolio-3.webp",
            "/projects/portafolio-4.webp",
            "/projects/portafolio-5.webp",
            "/projects/portafolio-6.webp",
            "/projects/portafolio-7.webp",
            "/projects/portafolio-8.webp",
        ],
        tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "React", "Responsive Design"],
        demoUrl: "https://camilo-portafolio.vercel.app/",
        githubUrl: "https://github.com/CamiloMaria/camilo-portafolio",
        featured: true,
        category: "frontend",
    },
    {
        id: 4,
        title: "NestJS Enterprise Boilerplate",
        description: "A robust boilerplate for NestJS with enterprise-level practices implemented using SOLID principles, designed to kickstart your backend development with a production-ready foundation.",
        longDescription:
            "This project offers an advanced structure for NestJS applications, implementing development best practices and enterprise architecture. The boilerplate includes environment configuration with validation using Joi, API documentation with Swagger/OpenAPI, API versioning, standardized response format, global exception handling, structured logging with nestjs-pino, rate limiting for abuse protection, health checks for application monitoring, and SWC compiler usage for faster development.",
        image: "/projects/boilerplate-1.webp",
        gallery: [
            "/projects/boilerplate-1.webp",
            "/projects/boilerplate-2.webp",
            "/projects/boilerplate-3.webp",
            "/projects/boilerplate-4.webp",
            "/projects/boilerplate-5.webp",
            "/projects/boilerplate-6.webp",
            "/projects/boilerplate-7.webp",
            "/projects/boilerplate-8.webp",
        ],
        tags: ["NestJS", "TypeScript", "SOLID", "API", "Swagger", "Enterprise", "Architecture", "Backend"],
        githubUrl: "https://github.com/CamiloMaria/nestjs-enterprise-boilerplate",
        featured: true,
        category: "backend",
    },
    {
        id: 5,
        title: "BeccaStudio - Photography Portfolio",
        description: "Professional website for a photographer, with image gallery, services, testimonials and session booking system.",
        longDescription:
            "I designed and developed this website for Rebeca Ramos (Becca), a Dominican professional photographer. The site includes an interactive portfolio gallery with filtered categories (portraits, commercial, 2x2, family sessions), services section, client testimonials, 'about me' page, and a photography session booking system. The website is optimized for mobile devices with an elegant design that reflects the photographer's artistic style, highlighting her work with intuitive navigation and fast image loading.",
        image: "/projects/becca-1.webp",
        gallery: [
            "/projects/becca-1.webp",
            "/projects/becca-2.webp",
            "/projects/becca-3.webp",
            "/projects/becca-4.webp",
            "/projects/becca-5.webp",
            "/projects/becca-6.webp",
        ],
        tags: ["Astro", "Tailwind CSS", "Responsive Design", "Photography", "Portfolio"],
        demoUrl: "https://beccastudio.com/",
        githubUrl: "https://github.com/CamiloMaria/beccastudio",
        featured: true,
        category: "frontend",
    },
    {
        id: 6,
        title: "AI Resume Analyzer",
        description: "A smart resume analysis tool that helps job seekers optimize their resumes for specific job applications using AI-powered feedback.",
        longDescription:
            "AI Resume Analyzer is an intelligent tool designed to help job seekers optimize their resumes using advanced AI technology. The application analyzes resumes against specific job descriptions and provides comprehensive feedback across multiple categories including ATS compatibility, tone and style, content quality, structure and formatting, and skills relevance. Built with React 19 and React Router 7, it features a modern responsive design, drag-and-drop PDF upload, visual preview capabilities, and cloud storage integration. The tool converts resumes to images for AI analysis and provides detailed scoring with actionable improvement suggestions to help users land their dream jobs.",
        image: "/projects/ai-resume-1.webp",
        gallery: [
        ],
        tags: ["React 19", "React Router 7", "TypeScript", "TailwindCSS", "PDF.js", "Puter.js", "Zustand", "Vite", "AI"],
        githubUrl: "https://github.com/CamiloMaria/ai-resume-analyzer",
        featured: true,
        category: "frontend",
    },
]

export default projects;