import { Project } from "@/types/project";

const projects: Project[] = [
    {
        id: 1,
        title: "Dashboard E-Commerce Plaza Lama",
        description: "Dashboard para e-commerce desarrollado desde cero, reemplazando una versión antigua en Angular con mejoras significativas de rendimiento.",
        longDescription:
            "Este dashboard para e-commerce fue creado completamente desde cero para Plaza Lama, sustituyendo una versión anterior desarrollada en una versión obsoleta de Angular. El proyecto mejoró el rendimiento en más de un 200% y automatizó numerosos procesos. Implementado con las mejores prácticas del framework, cuenta con una interfaz responsiva, gestión de inventario, y utiliza mocks para las llamadas a la API durante el desarrollo. Para loguearte, usa el usuario: admin y la contraseña: admin",
        image: "/projects/frontend-1.webp",
        gallery: [
            "/projects/frontend-1.webp",
            "/projects/frontend-2.webp",
            "/projects/frontend-3.webp",
            "/projects/frontend-4.webp",
            "/projects/frontend-5.webp",
        ],
        tags: ["React", "TypeScript", "Tailwind CSS", "Vite", "Tanstack", "Radix", "Zod"],
        demoUrl: "https://cm-dashboard-frontend.netlify.app/",
        githubUrl: "https://github.com/CamiloMaria/dashboard-frontend",
        featured: true,
        category: "frontend",
    },
    {
        id: 2,
        title: "Backend Dashboard E-Commerce",
        description: "API backend desarrollada con NestJS para soportar todas las funcionalidades del dashboard e-commerce de Plaza Lama.",
        longDescription:
            "Este proyecto constituye el backend que conecta toda la lógica del dashboard frontend para Plaza Lama. Desarrollado con las mejores prácticas de NestJS, implementa una arquitectura robusta para gestionar la autenticación, autorización y todas las operaciones de negocio. Utiliza TypeORM como ORM para la gestión de base de datos, JWT para la autenticación, Winston para logging, y está completamente probado con Jest.",
        image: "/projects/backend-1.webp",
        gallery: [
            "/projects/backend-1.webp",
            "/projects/backend-2.webp",
            "/projects/backend-3.webp",
            "/projects/backend-4.webp",
            "/projects/backend-5.webp",
        ],
        tags: ["NestJS", "TypeScript", "Node.js", "TypeORM", "JWT", "RxJS", "Jest"],
        githubUrl: "https://github.com/CamiloMaria/dashboard-backend",
        featured: true,
        category: "backend",
    },
    {
        id: 3,
        title: "Portafolio Personal",
        description: "Sitio web de portafolio personal desarrollado con Next.js, TypeScript y Tailwind CSS con animaciones interactivas y diseño responsivo.",
        longDescription:
            "Este portafolio personal fue diseñado y desarrollado desde cero utilizando tecnologías modernas para crear una experiencia web atractiva y profesional. Cuenta con secciones para mostrar proyectos, habilidades, experiencia y testimonios. Implementado con animaciones fluidas mediante Framer Motion y un diseño completamente responsivo que se adapta a cualquier dispositivo. El proyecto está estructurado siguiendo las mejores prácticas de desarrollo frontend y demuestra habilidades avanzadas en React y TypeScript.",
        image: "/projects/portafolio-1.webp",
        gallery: [
            "/projects/portafolio-1.webp",
            "/projects/portafolio-2.webp",
            "/projects/portafolio-3.webp",
            "/projects/portafolio-4.webp",
            "/projects/portafolio-5.webp",
            "/projects/portafolio-6.webp",
            "/projects/portafolio-7.webp",
            "/projects/portafolio-8.webp",
        ],
        tags: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "React", "Responsive Design"],
        demoUrl: "https://camilo-portafolio.vercel.app/",
        githubUrl: "https://github.com/CamiloMaria/camilo-portafolio",
        featured: true,
        category: "frontend",
    },
    {
        id: 4,
        title: "NestJS Enterprise Boilerplate",
        description: "Un robusto boilerplate para NestJS con prácticas de nivel empresarial implementadas usando principios SOLID, diseñado para iniciar tu desarrollo backend con una base lista para producción.",
        longDescription:
            "Este proyecto ofrece una estructura avanzada para aplicaciones NestJS, implementando las mejores prácticas de desarrollo y arquitectura empresarial. El boilerplate incluye configuración de entorno con validación usando Joi, documentación API con Swagger/OpenAPI, versionado de API, formato de respuestas estandarizado, manejo global de excepciones, logging estructurado con nestjs-pino, limitación de tasa de peticiones para protección contra abusos, revisiones de salud para monitoreo de aplicaciones y uso del compilador SWC para un desarrollo más rápido.",
        image: "/projects/boilerplate-1.webp",
        gallery: [
            "/projects/boilerplate-1.webp",
            "/projects/boilerplate-2.webp",
            "/projects/boilerplate-3.webp",
            "/projects/boilerplate-4.webp",
            "/projects/boilerplate-5.webp",
            "/projects/boilerplate-6.webp",
            "/projects/boilerplate-7.webp",
            "/projects/boilerplate-8.webp",
        ],
        tags: ["NestJS", "TypeScript", "SOLID", "API", "Swagger", "Enterprise", "Arquitectura", "Backend"],
        githubUrl: "https://github.com/CamiloMaria/nestjs-enterprise-boilerplate",
        featured: true,
        category: "backend",
    },
    {
        id: 5,
        title: "BeccaStudio - Portafolio de Fotografía",
        description: "Sitio web profesional para una fotógrafa, con galería de imágenes, servicios, testimonios y sistema de reservas de sesiones.",
        longDescription:
            "Diseñé y desarrollé este sitio web para Rebeca Ramos (Becca), una fotógrafa profesional dominicana. El sitio incluye una galería de portafolio interactiva con categorías filtradas (retratos, comercial, 2x2, sesiones familiares), sección de servicios, testimonios de clientes, página 'sobre mí' y un sistema de reserva de sesiones fotográficas. La web está optimizada para dispositivos móviles con un diseño elegante que refleja el estilo artístico de la fotógrafa, destacando sus trabajos con una navegación intuitiva y rápida carga de imágenes.",
        image: "/projects/becca-1.webp",
        gallery: [
            "/projects/becca-1.webp",
            "/projects/becca-2.webp",
            "/projects/becca-3.webp",
            "/projects/becca-4.webp",
            "/projects/becca-5.webp",
            "/projects/becca-6.webp",
        ],
        tags: ["React", "Next.js", "Tailwind CSS", "Framer Motion", "Responsive Design", "Fotografía", "Portafolio"],
        demoUrl: "https://beccastudio.com/",
        githubUrl: "https://github.com/CamiloMaria/beccastudio",
        featured: true,
        category: "frontend",
    },
    // {
    //     id: 6,
    //     title: "Backend Dashboard E-Commerce",
    //     description: "API backend desarrollada con NestJS para soportar todas las funcionalidades del dashboard e-commerce de Plaza Lama.",
    //     longDescription:
    //         "Este proyecto constituye el backend que conecta toda la lógica del dashboard frontend para Plaza Lama. Desarrollado con las mejores prácticas de NestJS, implementa una arquitectura robusta para gestionar la autenticación, autorización y todas las operaciones de negocio. Utiliza TypeORM como ORM para la gestión de base de datos, JWT para la autenticación, Winston para logging, y está completamente probado con Jest.",
    //     image: "/projects/backend-1.webp",
    //     gallery: [
    //         "/projects/backend-1.webp",
    //         "/projects/backend-2.webp",
    //         "/projects/backend-3.webp",
    //         "/projects/backend-4.webp",
    //         "/projects/backend-5.webp",
    //     ],
    //     tags: ["NestJS", "TypeScript", "Node.js", "TypeORM", "JWT", "RxJS", "Jest"],
    //     githubUrl: "https://github.com/CamiloMaria/dashboard-backend",
    //     featured: false,
    //     category: "backend",
    // },
]

export default projects;