import { Testimonial } from "@/types/testimonial";

const testimonials: Testimonial[] = [
    {
        id: 1,
        name: "Nurys Castillo",
        position: "CEO",
        company: "C&C Technology Supply",
        category: "tech",
        rating: 5,
        text: "¡Camilo es una joya! No solo trabaja rápido y con una eficiencia que sorprende, sino que también tiene un corazón enorme. En todos mis años en el mundo profesional, no he conocido a alguien con tanta disposición, calidez humana y ganas de ayudar. Siempre llega con una sonrisa, anima a todos a su alrededor, y hace que cualquier proyecto fluya con una energía increíble. Haberlo tenido en nuestro equipo ha sido una verdadera bendición.",
        highlight: "haberlo tenido en nuestro equipo ha sido una verdadera bendición",
        color: "from-purple-500 to-indigo-600",
        accentColor: "rgba(139, 92, 246, 0.8)",
        featured: true,
        country: "República Dominicana"
    },
    {
        id: 2,
        name: "Michael Chen",
        position: "Product Manager",
        company: "Innovate Solutions",
        category: "startup",
        rating: 5,
        text: "Camilo's attention to detail and commitment to quality is unmatched. He took our vague concept and transformed it into a beautiful, functional website that perfectly represents our brand. I highly recommend his services.",
        highlight: "attention to detail",
        color: "from-pink-500 to-rose-600",
        accentColor: "rgba(236, 72, 153, 0.8)",
        featured: false,
    },
    {
        id: 3,
        name: "Emily Rodriguez",
        position: "Marketing Director",
        company: "Global Brands",
        category: "marketing",
        rating: 4,
        text: "We hired Camilo to redesign our e-commerce platform, and the results were outstanding. The new site is not only visually stunning but also performs exceptionally well. Our conversion rates have increased by 40% since the launch.",
        highlight: "conversion rates increased by 40%",
        color: "from-amber-500 to-orange-600",
        accentColor: "rgba(245, 158, 11, 0.8)",
        featured: false,
    },
    {
        id: 4,
        name: "David Kim",
        position: "Founder",
        company: "StartUp Ventures",
        category: "startup",
        rating: 5,
        text: "As a startup founder with limited technical knowledge, I needed someone who could guide me through the development process. Camilo was patient, educational, and delivered a product that helped us secure our next round of funding.",
        highlight: "helped us secure our next round of funding",
        color: "from-emerald-500 to-teal-600",
        accentColor: "rgba(16, 185, 129, 0.8)",
        featured: false,
    },
    {
        id: 5,
        name: "Olivia Martinez",
        position: "UX Director",
        company: "Design Forward",
        category: "design",
        rating: 5,
        text: "I've worked with many developers, but Camilo stands out for his ability to translate design concepts into flawless code. His understanding of both design principles and technical implementation makes him a rare and valuable talent.",
        highlight: "translate design concepts into flawless code",
        color: "from-blue-500 to-cyan-600",
        accentColor: "rgba(59, 130, 246, 0.8)",
        featured: false,
    },
    {
        id: 6,
        name: "Thomas Wright",
        position: "E-Commerce Manager",
        company: "Retail Innovations",
        category: "ecommerce",
        rating: 5,
        text: "The custom e-commerce solution Camilo built for us has completely transformed our online business. The intuitive interface and seamless checkout process have significantly reduced cart abandonment and improved customer satisfaction.",
        highlight: "completely transformed our online business",
        color: "from-violet-500 to-purple-600",
        accentColor: "rgba(139, 92, 246, 0.8)",
        featured: false,
    },
]

export default testimonials;